#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd src

# Run tests
echo "Running tests..."
npm test
if [ $? -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "All checks passed!"
